# @package _group_

dpr_wiki:
    _target_: dpr.data.retriever_data.CsvCtxSrc
    file: data.wikipedia_split.psgs_w100
    id_prefix: 'wiki:'

xcodeeval:
    _target_: dpr.data.retriever_data.XcodeevalCtxSrc
    file: /home/zarzis/code/python/data/xCodeEval/retrieval_corpus/Python_code_retrieval_corpus.jsonl__041.jsonl
    id_prefix: 'xcodeeval_py_041:'
