# @package _group_

dpr_wiki:
    _target_: dpr.data.retriever_data.CsvCtxSrc
    file: data.wikipedia_split.psgs_w100
    id_prefix: 'wiki:'

xcl_rust:
    _target_: dpr.data.retriever_data.XCLRetCtxSrcPriv
    file: /home/zarzis/code/private/github/sbmaruf/dpr_xCodeEval/data/private/Rust_code_retrieval_metadata.jsonl
    id_prefix: 'xcl_cf_rust:'
